version: '3'
services:
  proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'proxy'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-webroot:/usr/share/nginx/html'

  letsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    container_name: 'letsencrypt'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-webroot:/usr/share/nginx/html'

  app1:
    image: nginx
    container_name: app1
    environment:
      VIRTUAL_HOST: api.shoxel.com
      LETSENCRYPT_HOST: api.shoxel.com
      LETSENCRYPT_EMAIL: 'admin@example.com'

  app2:
    image: nginx
    container_name: app2
    environment:
      VIRTUAL_HOST: shoxel.com
      LETSENCRYPT_HOST: shoxel.com
      LETSENCRYPT_EMAIL: 'admin@example.com'

  php-fpm:
    image: php-fpm
    container_name: php-fpm

volumes:
  nginx-vhosts:
  nginx-config:
  nginx-certs:
  nginx-webroot: