version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    hostname: shoxel.com
    ports:
      - "80:80"
      - "433:433"
    links:
      - app    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../:/var/www
      - ./images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ../letsencrypt/conf:/etc/letsencrypt
      - ../letsencrypt/html:/tmp/letsencrypt
    environment:
      - LE_RENEW_HOOK=docker kill -s HUP @CONTAINER_NAME@
    working_dir:
      /var/www/
  letsencrypt:
    restart: always
    image: kvaps/letsencrypt-webroot
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../letsencrypt/conf:/etc/letsencrypt
      - ../letsencrypt/html:/tmp/letsencrypt
    links:
      - nginx
    environment:
      - DOMAINS=shoxel.com www.shoxel.com
      - EMAIL=den4kox@gmail.com
      - WEBROOT_PATH=/tmp/letsencrypt
      - EXP_LIMIT=30
      - CHECK_FREQ=30
  app:
    build: ./images/php-fpm
    ports:
      - "9000:9000"
    links:
      - db  
    volumes:
      - ../:/var/www/
    working_dir:
      /var/www/meetbot
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meet
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - data:/var/lib/mysql
volumes:
    data: